New workflow test

diff --git a/.github/workflows/auto-update.yml b/.github/workflows/auto-update.yml
--- a/.github/workflows/auto-update.yml
+++ b/.github/workflows/auto-update.yml
@@ -80,7 +80,7 @@ jobs:
       #       --prefix "${BRANCH_NAME}" \
       #       --cache om \
       #       < $HOME/omci.json
-  flakehub-push:
+  build-flakes:
     permissions:
       id-token: "write"
       contents: "read"
@@ -125,15 +125,12 @@ jobs:
 
       - name: Checkout repository
         uses: actions/checkout@v5
-        with:
-          persist-credentials: false
 
       - name: Install Determinate Nix
-        uses: DeterminateSystems/nix-installer-action@main
-        # uses: DeterminateSystems/determinate-nix-action@v3
+        uses: DeterminateSystems/determinate-nix-action@v3
 
-      - name: Set up GitHub Actions cache
-        uses: DeterminateSystems/magic-nix-cache-action@main
+      # - name: Set up GitHub Actions cache
+      #   uses: DeterminateSystems/magic-nix-cache-action@main
 
       - name: Set up FlakeHub cache
         uses: DeterminateSystems/flakehub-cache-action@main
@@ -166,6 +163,31 @@ jobs:
             --systems "${{ matrix.system }}" \
             --results=$HOME/omci.json \
             -- --accept-flake-config
+
+  flakehub-push:
+    runs-on: ubuntu-latest
+    needs: build-flakes
+    if: ${{ always() }}
+    permissions:
+      id-token: write
+      contents: read
+    steps:
+      - name: Check build results
+        run: |
+          echo "A dependent in the build matrix failed."
+          exit 1
+        if: |
+          contains(needs.*.result, 'failuire') ||
+          contains(needs.*.result, 'cancelled')
+
+      - name: Checkout repository
+        uses: actions/checkout@v5
+
+      - name: Set up Determinate Nix
+        uses: DeterminateSystems/determinate-nix-action@v3
+
+      - name: Set up FlakeHub cache
+        uses: DeterminateSystems/flakehub-cache-action@main
 
       - name: Push to FlakeHub
         uses: DeterminateSystems/flakehub-push@main
